---
title: "Sdaouki_Assignment14"
author: "Saloua Daouki"
date: "2024-04-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This week, we’ll work out some Taylor Series expansions of popular functions.

$f (x) = \frac{1}{(1−x)}$

$f (x) = e^x$

$f (x) = ln(1 + x)$

$f(x)=x^{\frac{1}{2}}$

For each function, only consider its valid ranges as indicated in the notes when you are computing the Taylor Series expansion. Please submit your assignment as an R- Markdown document.

## **1.**  $f (x) = \frac{1}{(1−x)}$

This function cannot take $x=1$ so its valid range is $\mathbb{R} \setminus \{1\}$ or $(- \infty , 1) \cup (1, \infty)$

So the Taylor series expansion of this function at $x=0$ is

$\frac{1}{1-x} = \sum_{n=0}^{\infty} x^n$

## **2.** $f (x) = e^x$

The valid range for this function is all real numbers $\mathbb{R}$ or $(- \infty, \infty)$

So the Taylor series expansion of this function at $x=0$ is

$e^x = \sum_{n=0}^{\infty} \frac{x^n}{n!}$

## **3.** $f (x) = ln(1 + x)$

"ln" function is only defined on only posituve real numbers $\mathbb{R^+}$ so

$$
\begin{align}
1+x&>0\\
x&>-1\\
\end{align}
$$

So the valid range of $ln(1+x)$ is $(-1, \infty)$

We know that $ln(x) = \sum_{n=0} ^{\infty} (-1)^{n+1} \frac{(x-1)^n}{n}$

$\Rightarrow$ to find the Taylor series for $ln(1+x)$ at $x=0$, we substitute $(1+x)$ for $x$:

$$
\begin{align}
ln(1+x) &= \sum _{n=0} ^ {\infty} (-1)^{n+1} \frac{((1+x)-1)^n}{n}\\
&= \sum _{n=0} ^ {\infty} (-1)^{n+1} \frac{x^n}{n}\\
\end{align}
$$

## 4.  $f(x)=x^{\frac{1}{2}}$

This function can be also written as $f(x) = \sqrt x$ which is defined on the positive real numbers including 0 \$ \mathbb{R}\_{\geq 0} \$ but we are going to find the Taylor series expansion at $x=1$ since we cannot evaluate the derivatives at $x=0$ since it will be undefined:

$$
\begin{align}
f(x) &= \sqrt x \qquad \Rightarrow f(1) = 1 \\
f'(x) &= \frac{1}{2 \sqrt{x}} \quad \Rightarrow f'(1) = \frac{1}{2} \\
f''(x) &= \frac{-1}{4x^{\frac{3}{2}}} \quad \Rightarrow f''(1) = \frac{-1}{4} \\
f'''(x) &= \frac{3}{8 x ^ {\frac{5}{2}}} \quad \Rightarrow f'''(1) = \frac{3}{8}\\
f^{(4)} (x) &= \frac{-15}{16 x ^\frac{7}{2}} \quad \Rightarrow f^{(4)} (1) = \frac{-15}{16}\\
f^{(5)} (x) &= \frac{105}{32 x^{\frac{9}{2}}} \quad \Rightarrow f^{(5)} (1) = \frac{105}{32}
\end{align}
$$

So the Taylor series Expansion of $x^{\frac{1}{2}}$ is:

$x^{\frac{1}{2}} = 1 + \frac{1}{2} (x-1) - \frac{1}{8} (x-1)^2 + \frac {1}{48} (x-1)^3 - \frac{5}{384} (x-1)^4 + \frac{35}{1536} (x-1)^5$

We also know that $(1+x)^k = \sum_{n=0}^{\infty} \frac{k(k-1)...(k-(n-1))}{n!} x^n$

For $k=\frac{1}{2}$ we get:

$$
\begin{align}
(1+x)^{\frac{1}{2}} &= \sum_{n=0}^{\infty} \frac{\frac{1}{2}(\frac{1}{2}-1)...(\frac{1}{2}-(n-1))}{n!} x^n\\
&= \sum_{n=0}^{\infty} \frac{\frac{1}{2}(\frac{1}{2}-1)...(\frac{2n-3}{2})}{n!} x^n\\
&= \sum_{n=0}^{\infty} \frac{(-1)^{n-1} (2n-3)!!}{2^nn!} x^n\\
\end{align}
$$
