---
title: "Week_3_Discussion"
output: html_document
date: "2024-02-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question C11 page 306

Find the characteristic polynomial of the matrix $A=\begin{bmatrix} 3 & 2 & 1\\ 0 & 1 & 1\\ 1 & 2 & 0\end{bmatrix}$


To find the characteristic polynomial, we need to find $\lambda I_3 - A$ where $\lambda$ is the eigenvalue, $I_3$ is the $3\times3$ identity matrix and A is the given matrix


$\Rightarrow \lambda I_3 - A = \left(\begin{bmatrix} \lambda & 0 & 0\\ 0 & \lambda & 0\\ 0 & 0 & \lambda\end{bmatrix}-\begin{bmatrix} 3 & 2 & 1\\ 0 & 1 & 1\\ 1 & 2 & 0\end{bmatrix}\right)$


$\Rightarrow det(\lambda I_3 - A)= det\begin{bmatrix} \lambda-3 & -2 & -1\\ 0 & \lambda-1 & -1\\ -1 & -2 & \lambda\end{bmatrix}$


$det(\lambda I_3 - A)= (\lambda-3)(\lambda-1)(\lambda) - 2 - 2(\lambda-3) - (\lambda-1)$


$det(\lambda I_3 - A)= (\lambda^2 - 4 \lambda +3) \lambda -2 -2 \lambda + 6 - \lambda +1$


$det(\lambda I_3 - A)= \lambda^3 -4 \lambda^2 +3 \lambda + 5 -3 \lambda$


$p(x) = \lambda^3 - 4 \lambda^2 + 5$


$p(x)$ is the characteristic polynomial of the matrix $A=\begin{bmatrix} 3 & 2 & 1\\ 0 & 1 & 1\\ 1 & 2 & 0\end{bmatrix}$

## Question T10 page 317:

Suppose that A is a square matrix. Prove that the constant term of the characteristic polynomial of A is equal to the determinant of A.

Let A be a square matrix with 2 dimension $2\times2$

$A=\begin{bmatrix} a & b\\ c & d\end{bmatrix}$

To prove that the constant of the characteristic polynomial is equal to the determinant of A, let's find the characteristic polynomial of A first:

$\Rightarrow det(\lambda I_2 - A)= \left(\begin{bmatrix} \lambda & 0\\ 0 & \lambda\end{bmatrix} - \begin{bmatrix} a & b\\ c & d\end{bmatrix}\right)$


$\Rightarrow det(\lambda I_2 - A)= \left(\begin{bmatrix} \lambda-a & -b \\ -c & \lambda-d\end{bmatrix}\right)$


$\Rightarrow det(\lambda I_2 - A)= (\lambda-a) (\lambda-d) - (cb)$


$\Rightarrow det(\lambda I_2 - A)= \lambda^2 -d \lambda - a \lambda + ad - cb$


$\Rightarrow p(x) = \lambda^2 - \lambda(d+a) + (ad-cb)$


The constant of $p(x)$ is equal to $(ad-cb)$ and $det(A)=ad-cb$, So the constant of $p(x)$ and the determinant of the matrix $A=\begin{bmatrix} a & b\\ c & d\end{bmatrix}$ are equal.
